version: '3'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/webhookDB

  mongo:
    image: mongo
    ports:
      - "27017:27017"
